[platformio]
src_dir=firmware/smart-entryway-usage-analytics
[env:nodemcuv2]
platform=espressif8266@4.2.1
board=nodemcuv2
framework=arduino
monitor_speed=115200
lib_deps=
  adafruit/Adafruit BME280 Library@2.2.4
  adafruit/Adafruit SSD1306@2.5.13
  knolleary/PubSubClient@2.8
